site:
  title: ownCloud Android Documentation
  url: https://owncloud-docs.netlify.com/ 

content:
  sources:
  - url: https://github.com/owncloud/android.git
    branches: 
    - master-antora
    start_path: docs/

ui:
  bundle:
    url: https://minio.owncloud.com/documentation/ui-bundle.zip
  output_dir: assets

output:
  clean: true
  dir: public
